name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '4.0.11'

      - name: Build with emcc
        run: |
          chmod +x build.sh
          ./build.sh emcc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4